### ISSUE TITLE
separate set up for each component

### ISSUE THREAD

**Issue by Mehdi203** [jufab/opentelemetry-angular-interceptor#104]
I've successfully added the instrumentation. I'm capturing the traces but the current set up configure the traces globally. I get the same service name on Zipkin for all different components that I have in the application. I'm wondering if it's possible to customize the service name for each different component in the application? I basically would like to have a unique service name on Zipkin based on the url that I call from the browser. Just a quick note that I'm looking to capture the traces for the frontend only. Please let me know if this is possible?

**Comment by jufab** [comment]
Hi,

In this library, no, it's impossible. 
if you make your own implementation, you probably can do that : you must redefine ressource attribute with service name
