### ISSUE TITLE
Zipkin exporter

### ISSUE THREAD

**Issue by Booster2ooo** [jufab/opentelemetry-angular-interceptor#11]
Hello,

I just want to provide some more info about Zipkin exporter because it's in a grey area right now for the web browser support.

In the [ZipkinExporterService](https://github.com/jufab/opentelemetry-angular-interceptor/blob/master/projects/opentelemetry-interceptor/src/lib/services/exporter/zipkin-exporter.service.ts), it's is stated that ```ZipkinExporter isn't operationnal for the moment in web application.``` which isn't 100% true.

The Opentelemetry Zipkin exporter is based on few node.js global modules such as http and https which should make the library [incompatible with the browser](https://github.com/open-telemetry/opentelemetry-js/issues/1265). Nevertheless, webpack provides some [polyfills](https://webpack.js.org/configuration/node/) that makes it [possible to run the Zipkin exporter in the browser](https://codesandbox.io/s/otel-zipkin-exporter-browser-simple-51slu?file=/index.ts).

By default, Angular's webpack configuration turns off node polyfills (node: false) but it's possible to extend the webpack configuration to turn it on thus making Zipkin exporter work.

To do so, some simple steps are required:

- Install the npm package ```@angular-builders/custom-webpack```
- Change the project build builder in ```angular.json``` (projects._project-name_.architect.build.builder)
```
-- "builder": "@angular-devkit/build-angular:browser",
++ "builder": "@angular-builders/custom-webpack:browser",
```
- Add a customWebpackConfig in the project build options in ```angular.json``` (projects._project-name_.architect.build.options):
```
++  "customWebpackConfig": {
++    "path": "./webpack.config-extension.js"
++  },
    "aot": true,
    "progress": true,
    "extractCss": true,
    "outputPath": "dist",
  ...
```
- (Optional) Change the project serve builder in ```angular.json``` (projects._project-name_.architect.serve.builder)
```
-- "builder": "@angular-devkit/build-angular:dev-server",
++ "builder": "@angular-builders/custom-webpack:dev-server",
```
- Add ```webpack.config-extension.js``` at the same level than angular.json
```Javascript
module.exports = {
  node: {
    global: true
  }
}
```

With this manipulation, the module ```@opentelemetry/exporter-zipkin``` can be used in Angular (and, by extension, in the browser). 

It is important to note that I don't know the possible side-effects of allowing node globals in the webpack configuration and the impact on the Angular app.

**Comment by jufab** [comment]
Hi,  

Thanks for that!

I started a branch with your suggestion => https://github.com/jufab/opentelemetry-angular-interceptor/tree/zipkin_webpack  

It works   

But this modification is possible only on the application, not on the library. So if i insert that, this library will be not compatible with a default angular application (ng new)

I prefer to wait for a zipkin "browser" compatible.

I conserve this branch for the moment  ;)

**Comment by Booster2ooo** [comment]
This is indeed purely informative, it's a good way to "pre-test" the zipkin exporter and for users to have some pieces of information on how to setup the zipkin exporter with an angular project.

I totally understand and agree with you, it's best to wait for the official browser support.

**Comment by Booster2ooo** [comment]
FYI, Zipkin is officially supported in browser now: https://github.com/open-telemetry/opentelemetry-js/pull/1399#event-3726270877

**Comment by jufab** [comment]
Thanks.

I just wait the next release ;)
