### ISSUE TITLE
Exclude URLs

### ISSUE THREAD

**Issue by sebaparedero14** [jufab/opentelemetry-angular-interceptor#111]
Hello,

I am using the global interceptor and I need to know if there is a way to exclude certain urls to avoid header propagation?

Thanks!

**Comment by sebaparedero14** [comment]
Hi @jufab,

 I made a modification in the configuration to add an array with the urls to ignore.

Check: #116

**Comment by jufab** [comment]
Done @sebaparedero14 

=> https://github.com/jufab/opentelemetry-angular-interceptor/releases/tag/v1.1.0-2

Thanks for your contribution
