### ISSUE TITLE
HTTP 400 "unknown field "scopeSpans" in v1.ResourceSpans"

### ISSUE THREAD

**Issue by mtoppaize** [jufab/opentelemetry-angular-interceptor#112]
Hi,

Trying to setup in Angular 13 project but getting the following error when trying to send to localhost:4318/v1/traces (closely following your interceptor-example), I have docker compose spun up with Jaeger and Otel Collector which is working for API, have configured for CORS and mapping 4318. 

HTTP 400 Bad Request
{code: 3, message: "unknown field "scopeSpans" in v1.ResourceSpans"}
code: 3
message: "unknown field \"scopeSpans\" in v1.ResourceSpans"

The payload I can see loads of information from the app.

Any ideas?

**Comment by sebaparedero14** [comment]
Hi,

I had the same problem when the @opentelemetry/exporter-trace-otlp-http library was updated.

In my case I downgraded to version @0.0.27 to make it work.

**Comment by mtoppaize** [comment]
Hi, thanks for the quick responses. 

Downgrading as @sebaparedero14 mentioned has resolved the issue and the telemetry is now showing in Jaeger (Angular 13.2.1). 
    "@jufab/opentelemetry-angular-interceptor": "1.1.0",
DevDependancies
    "@opentelemetry/api": "1.1.0",
    "@opentelemetry/context-zone-peer-dep": "1.2.0",
    "@opentelemetry/core": "1.3.1",
    "@opentelemetry/exporter-trace-otlp-http": "0.28.0",
    "@opentelemetry/exporter-zipkin": "1.2.0",
    "@opentelemetry/instrumentation": "0.28.0",
    "@opentelemetry/propagator-jaeger": "1.2.0",
    "@opentelemetry/resources": "1.3.1",
    "@opentelemetry/sdk-trace-base": "1.3.1",
    "@opentelemetry/sdk-trace-web": "1.2.0",
    "@opentelemetry/semantic-conventions": "1.3.1",

I bumped to 1.1.0-1 @jufab but issue has remained for me. 
    "@jufab/opentelemetry-angular-interceptor": "1.1.0-1",
devDependancies
    "@opentelemetry/api": "1.1.0",
    "@opentelemetry/context-zone-peer-dep": "1.3.1",
    "@opentelemetry/core": "1.3.1",
    "@opentelemetry/exporter-trace-otlp-http": "0.29.2",
    "@opentelemetry/exporter-zipkin": "1.3.1",
    "@opentelemetry/instrumentation": "0.29.2",
    "@opentelemetry/propagator-jaeger": "1.3.1",
    "@opentelemetry/resources": "1.3.1",
    "@opentelemetry/sdk-trace-base": "1.3.1",
    "@opentelemetry/sdk-trace-web": "1.3.1",
    "@opentelemetry/semantic-conventions": "1.3.1",

**Comment by jufab** [comment]
@mtoppaize 
Can you please try now with : 

```
"@jufab/opentelemetry-angular-interceptor": "^1.1.0-2",

 "@opentelemetry/api": "^1.1.0",
  "@opentelemetry/context-zone-peer-dep": "^1.4.0",
  "@opentelemetry/core": "^1.4.0",
  "@opentelemetry/exporter-trace-otlp-http": "^0.30.0",
  "@opentelemetry/exporter-zipkin": "^1.4.0",
  "@opentelemetry/instrumentation": "^0.30.0",
  "@opentelemetry/propagator-aws-xray": "^1.1.0",
  "@opentelemetry/propagator-b3": "^1.4.0",
  "@opentelemetry/propagator-jaeger": "^1.4.0",
  "@opentelemetry/sdk-trace-web": "^1.4.0",
```

**Comment by squarewave24** [comment]
having the same exact issue with newly installed libraries 

```
@opentelemetry/instrumentation-http outgoingRequest on request close()
{
    "stack":"OTLPExporterError: Bad Request
        at IncomingMessage.<anonymous> (/.../node_modules/@opentelemetry/otlp-exporter-base/src/platform/node/util.ts:131:27)
        at /.../node_modules/@opentelemetry/context-async-hooks/src/AbstractAsyncHooksContextManager.ts:75:49
        at AsyncLocalStorage.run (node:async_hooks:309:14)
        at AsyncLocalStorageContextManager.with (/.../node_modules/@opentelemetry/context-async-hooks/src/AsyncLocalStorageContextManager.ts:40:36)
        at IncomingMessage.contextWrapper (/.../node_modules/@opentelemetry/context-async-hooks/src/AbstractAsyncHooksContextManager.ts:75:26)
        at IncomingMessage.emit (node:events:402:35)
        at IncomingMessage.emit (node:domain:475:12)
        at endReadableNT (node:internal/streams/readable:1343:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21)",
    "message":"Bad Request",
    "name":"OTLPExporterError",
    "data":"{\"code\":3,\"message\":\"unknown field \\\"scopeSpans\\\" in v1.ResourceSpans\"}",
    "code":"400"
 }
```

installed versions:
```
    "@apollo/gateway": "^2.3.4",
    "@opentelemetry/api": "1.4.1",
    "@opentelemetry/auto-instrumentations-node": "^0.36.4",
    "@opentelemetry/core": "1.10.0",
    "@opentelemetry/exporter-trace-otlp-http": "^0.36.0",
    "@opentelemetry/instrumentation-express": "0.32.1",
    "@opentelemetry/instrumentation-http": "0.36.0",
    "@opentelemetry/resources": "1.10.0",
    "@opentelemetry/sdk-trace-base": "1.10.0",
    "@opentelemetry/sdk-trace-node": "1.10.0",
    "@tsconfig/node16": "^1.0.3",
    "apollo-server": "^3.12.0",
```

**Comment by squarewave24** [comment]
follow up, per @sebaparedero14 advice i downgraded below library and that fixed the issue:

```
"@opentelemetry/exporter-trace-otlp-http": "0.27.0",
```
