### ISSUE TITLE
Injecting TraceId and SpanId into Logs

### ISSUE THREAD

**Issue by Mehdi203** [jufab/opentelemetry-angular-interceptor#118]
Is it possible to Inject TraceIds and SpanIds into Logs similar to what's available for JavaScript (example in the following link): 
 
[JavaScript TraceId and SpanId injection into logs](https://help.sumologic.com/Traces/01Getting_Started_with_Transaction_Tracing/01Instrument_your_application_with_OpenTelemetry/JavaScript_OpenTelemetry_auto-instrumentation/JavaScript_TraceId_and_SpanId_injection_into_logs)

**Comment by jufab** [comment]
Hi @Mehdi203,

You can do it with the CustomSpan interface. 

See more information about this [here](https://github.com/jufab/opentelemetry-angular-interceptor#optional-add-span-attributes-during-interception)

And you can do it like 

```typescript
  add(span: Span, request: HttpRequest<unknown>, response: HttpResponse<unknown> | HttpErrorResponse): Span {
    span.setAttribute(this.myKey , request.params + ';' + response.status);
    console.log(`Example log trace_id:”${span.spanContext().traceId}” span_id:”${span.spanContext().spanId}” trace_flags:”${span.spanContext().traceFlags}”`);
    return span;
  }
```
