### ISSUE TITLE
No propagator headers added to my http requests when select Instrumentation Module with XMLHttpRequestInstrumentation

### ISSUE THREAD

**Issue by suxiaoxiaomm** [jufab/opentelemetry-angular-interceptor#144]
Hi,
I am trying to apply web instrumentation, while I found with this module, and applied CompositePropagatorModule, I expect to see my http requests have B3, W3C, etc. applied to its headers, which can be used when propagating this request to to my backend services, which are dotnet services.

It works fine when I select interceptorModule. I can see my http requests have all those headers applied, and the span context can be propagated to my backend spans.

Is there any other configuration that I missed?

Appreciate your help!

What I expect:
![image](https://user-images.githubusercontent.com/33482742/209747021-520f2fb9-6993-4f0c-9fe4-3f294cc4379e.png)

Currently it has no B3, W3C, or any other propagation headers:
![image](https://user-images.githubusercontent.com/33482742/209747168-207b960e-6580-4b48-aaca-a4ce58ddec23.png)

**Comment by jufab** [comment]
Hi @suxiaoxiaomm 

Interceptor manually injects headers on the request.
Instrumentation automatically add headers on each request.

Do you see if you don't have CORS issues and do you had the `propagateTraceHeaderCorsUrls` configuration on XMLHttpRequestInstrumentation?

Like :

```javascript
providers: [
    {provide: OTEL_INSTRUMENTATION_PLUGINS, useValue: [new XMLHttpRequestInstrumentation({
      propagateTraceHeaderCorsUrls: ['http://localhost:3000/api/']
    })]}
  ],
```

more info here => https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-instrumentation-xml-http-request
