### ISSUE TITLE
Error with angular 14, type error cannot read properties of undefined reading OTEL_SDK_DISABLED

### ISSUE THREAD

**Issue by SarthakSakhare** [jufab/opentelemetry-angular-interceptor#147]
Getting Error with angular 14, type error cannot read properties of undefined reading OTEL_SDK_DISABLED. Any insight would be appreciated

**Comment by jufab** [comment]
Hi @SarthakSakhare,

Do you have more information like configuration or libraries versions used?

OTEL_SDK_DISABLED is an env var from specification => https://opentelemetry.io/docs/reference/specification/sdk-environment-variables/#general-sdk-configuration
