### ISSUE TITLE
Cannot exclude requests from being traced

### ISSUE THREAD

**Issue by hriddhighosh4** [jufab/opentelemetry-angular-interceptor#151]
I have instrumented an angular app which uses google oauth  client (openid-connect).
I am getting the error 
```
Access to XMLHttpRequest at 'https://accounts.google.com/.well-known/openid-configuration' from origin 'https://staging-console.mykaarma.dev' has been blocked by CORS policy: Request header field x-b3-traceid is not allowed by Access-Control-Allow-Headers in preflight response.
```
tracing includes some extra headers in my request which is not recognised by the library and it gives a CORS error.

I can see in [opentelemtry js](https://github.com/open-telemetry/opentelemetry-js/blob/ef6fcdcd1a7e5234758e3bcc9ff6c29db5ff4d23/experimental/packages/opentelemetry-instrumentation-http/README.md#L59) ,  `opentelemetry-instrumentation-http` package there are options `ignoreOutgoingRequestHook` and `ignoreIncomingRequestHook`. Is there any way to use it with this library as well?

**Comment by jufab** [comment]
Hi @hriddhighosh4,

Do you use instrumentation or interceptor?

If it's interceptor, in configuration you can use `ignoreUrls` in configuration => https://github.com/jufab/opentelemetry-angular-interceptor/blob/93980606482a28a3e7fc7a3099170213ebc5fc78/projects/opentelemetry-interceptor/src/lib/configuration/opentelemetry-config.ts#L127
_I see I haven't documented this part... I will use this issue to fix it_

If it's instrumentation, it depends on plugin you use. if it's @opentelemetry/instrumentation-xml-http-request you can add `propagateTraceHeaderCorsUrls` configuration => https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-instrumentation-xml-http-request
