### ISSUE TITLE
Clarification on traceId value

### ISSUE THREAD

**Issue by sansp00** [jufab/opentelemetry-angular-interceptor#152]
I am currently integrating this as a mean to populate the X-B3 headers and was wondering what was the expected behavior of the traceId value ? I am currently getting a new traceId value per call in my app, but was expecting a single traceId but different spans. What should be expected ?

Using Anglar 13, 
OpenTelemetryInterceptorModule.forRoot(environment.opentelemetryConfig),

NoopSpanExporterModule,
CompositePropagatorModule,
B3PropagatorModule,

opentelemetryConfig: {
    commonConfig: {
      console: true,
      production: false,
      logBody: true, 
      serviceName: 'interceptor-example', 
      probabilitySampler: '1', 
      logLevel:DiagLogLevel.ALL 
    },
   b3PropagatorConfig: {
     multiHeader: '1'
    }
  }

Thanks

**Comment by jufab** [comment]
Hi @sansp00,

Maybe this documentation can help you to understand https://opentelemetry.io/docs/reference/specification/overview/#tracing-signal
