### ISSUE TITLE
Adding additional resource attributes

### ISSUE THREAD

**Issue by ConradWeiser** [jufab/opentelemetry-angular-interceptor#156]
Hey there!

I'm looking to utilize this library to point to a collector which eventually dumps out to [Application Dynamics](https://www.appdynamics.com/). One of their requirements is that a `service.name` and a `service.namespace` resource attribute is set.

I see the `service.name` is filled out in the `CommonCollectorConfig` interface, though I can't seem to find a place to apply custom attributes to the resource. [Span Attributes](https://github.com/jufab/opentelemetry-angular-interceptor#optional-add-span-attributes-during-interception) details a way which would work great for this, is there a way this can be done for resources as well, as opposed to just giving it to each individual span? Though truthfully that might be a little overkill for each resource, maybe just an array of interfaces which can be added including a `attribute.name` and `attribute.value` would work just fine.

I can override this in the collector, though I'd prefer that this gets set on the application instead since the collector is used by multiple namespaces.

If there isn't anything for this, I can look to build out a Pull Request, just wanted to ensure I wasn't missing some functionality first.

**Comment by ConradWeiser** [comment]
Realistically, this is all that I need for my application:

See commit in Fork: https://github.com/jufab/opentelemetry-angular-interceptor/commit/9230447dd5129ceafe41055c4cb83ad780d0c47e (Pending documentation adjustments)

Though realistically, I figure it might be better if the config accepts a mapping of `SemanticResourceAttributes` where some are required and others are not. (Really, just the name SHOULD be required)

If you're open to a more involved resource attribute configuration with a little more flexibility, I can look to build out that fork branch to run by for approval.

**Comment by jufab** [comment]
Hi @ConradWeiser,

I agree with you : this lib and its configuration need a possibility to add resource attributes.

I work on it with a map of ressource attributes.

Stay tuned

**Comment by jufab** [comment]
You can use version 1.4.0-1 with the new `resourceAttributes` configuration ;)
