### ISSUE TITLE
Missing relevant trace headers for frontend and backend spans linking

### ISSUE THREAD

**Issue by dilbwagsingh** [jufab/opentelemetry-angular-interceptor#162]
## Problem
I am trying to instrument our frontend applications too using this library. But what I noticed is that for a particular angular app, trace headers are not passed on to the backend requests thus rendering the frontend and backend spans of the same request in different traces.

## Expectation
Proper headers should pass to the backend calls as well and the spans of the backend and frontend for the same request should be shown in a single trace.

> Note: This behaviour is happening only for one of our angular app. In the past we used the same method to instrument other angular apps and they work as expected. 

## Things I tried
- Updating package.json to latest dependencies 
- Compared code with other working angular apps <- No difference as such
- Checked for angular version discrepancies but none found

## My ask of the community
- What could be the possible solution here? 
- Why is this happening that other angular apps are working fine except this?

Thank you!!

### Tracing backend 
Jaeger with AWS ElasticSearch as storage backend and AWS MSK as secondary storage.

### `package.json` dependencies version of the not working app
```
"@angular/animations": "~13.1.1",
"@angular/cdk": "~13.1.1",
"@angular/common": "~13.1.1",
"@angular/compiler": "~13.1.1",
"@angular/core": "~13.1.1",
"@angular/forms": "~13.1.1",
"@angular/material": "~13.1.1",
"@angular/platform-browser": "~13.1.1",
"@angular/platform-browser-dynamic": "~13.1.1",
"@angular/router": "~13.1.1",
"@jufab/opentelemetry-angular-interceptor": "^1.4.1",
"@opentelemetry/api": "^1.4.1",
"@opentelemetry/context-zone-peer-dep": "^1.11.0",
"@opentelemetry/core": "^1.11.0",
"@opentelemetry/exporter-trace-otlp-http": "^0.35.1",
"@opentelemetry/exporter-zipkin": "^1.11.0",
"@opentelemetry/instrumentation": "^0.35.1",
"@opentelemetry/instrumentation-document-load": "^0.31.2",
"@opentelemetry/instrumentation-fetch": "^0.35.1",
"@opentelemetry/instrumentation-xml-http-request": "^0.35.1",
"@opentelemetry/propagator-aws-xray": "^1.2.0",
"@opentelemetry/propagator-b3": "^1.11.0",
"@opentelemetry/propagator-jaeger": "^1.11.0",
"@opentelemetry/resources": "^1.11.0",
"@opentelemetry/sdk-trace-base": "^1.11.0",
"@opentelemetry/sdk-trace-web": "^1.11.0",
"@opentelemetry/semantic-conventions": "^1.11.0",
```

### Code addition for instrumenting (`app.module.ts` file)
```
import {
  OpenTelemetryInterceptorModule,
  OtelColExporterModule,
  CompositePropagatorModule,
} from '@jufab/opentelemetry-angular-interceptor';

imports: [
    ...
    OpenTelemetryInterceptorModule.forRoot({
      commonConfig: {
        console: true,
        production: environment.production,
        serviceName: 'abc-service',
        probabilitySampler: '1.0',
      },
      batchSpanProcessorConfig: {
        maxQueueSize: '5096', 
        maxExportBatchSize: '1024',
        scheduledDelayMillis: '2000', 
        exportTimeoutMillis: '30000',
      },
      otelcolConfig: {
        url: environment.tracingCollectorUrl,
      },
    }),
    OtelColExporterModule,
    CompositePropagatorModule,
    ...
]
```

### Angular app working fine 
![image](https://user-images.githubusercontent.com/44468730/230470659-5e0ef538-749d-4518-9e91-438c32e89214.png)

### Angular app with the issue
![image](https://user-images.githubusercontent.com/44468730/230470596-e649afe0-7a92-4c54-a6e4-c3857174492d.png)

**Comment by hriddhighosh4** [comment]
@jufab can you please help out.We are stuck with this issue.

**Comment by dilbwagsingh** [comment]
Found the issue. There was an issue in our `auth.interceptor.ts` file of the service, where it was programmed to intercept the headers and create a new header. Thus, unintentionally discarding the existing ones.
Closing this issue now.
