### ISSUE TITLE
Wrong dependency version

### ISSUE THREAD

**Issue by lnu** [jufab/opentelemetry-angular-interceptor#190]
Hello,

We use the latest version(1.7.0) and we noticed an incorrect version in the package.json(extrat dot at the end): 
downloadesd version
<img width="409" alt="image" src="https://github.com/jufab/opentelemetry-angular-interceptor/assets/1829553/e4a1b3a8-9cf6-4ed6-8c36-cc8e98b58f18">

repo version
<img width="987" alt="image" src="https://github.com/jufab/opentelemetry-angular-interceptor/assets/1829553/1314965e-d5e9-4b51-9ea7-b43583f6960b">

**Comment by jufab** [comment]
Hi @lnu,

I fixed this on version 1.7.0-1 which was just released.

**Comment by jufab** [comment]
Fix in #191
