### ISSUE TITLE
Jaeger connection refused.

### ISSUE THREAD

**Issue by josi02** [jufab/opentelemetry-angular-interceptor#24]
Hi,

I'm trying to send trace to Jaeger collector based on wiki documentation from an Angular 10 app.

My config:
```
opentelemetryConfig: {
    commonConfig: {
      console: true,
      production: false,
      serviceName: 'frontend-app',
      probabilitySampler: '1'
    },
    otelcolConfig: {
      url: 'http://localhost:55681/v1/trace'
    },
    jaegerPropagatorConfig: {
      customHeader: 'custom-header'
    }
  }
```

In app.module.ts:
```
  ...
  OpenTelemetryInterceptorModule.forRoot(environment.opentelemetryConfig),
  OtelColExporterModule,
  JaegerHttpTracePropagatorModule
```

But I got the following error in console: POST http://localhost:55681/v1/trace net::ERR_CONNECTION_REFUSED
And traces are not showing in Jaeger. (FYI: .NET backend application sends traces successfully to Jaeger)

I tried both docker and bianry distribution of jaeger-all-in-one. From here: https://www.jaegertracing.io/docs/1.20/getting-started/

Can you please help me what I'm doing wrong?

Thanks

**Comment by jufab** [comment]
Hi @josi02 ,

If i understand, you want to use jaeger as collector.

Jaeger collector have no port 55681, this is http port for opentelemetry-collector => You use opentelemetry-collector (otelcol) exporter in your app.module.ts (OtelColExporterModule)

you can see here https://github.com/jufab/opentelemetry-angular-interceptor#optional-result-in-opentelemtery-collector for an exemple of integration in Jaeger (you use otelcol receiver who sends your span to Jaeger) and here https://github.com/open-telemetry/opentelemetry-collector/blob/master/docs/design.md to understand otelcol configuration

JaegerHttpTracePropagator is use to send trace id in your backend request (you must see a "uber-trace-id: xxxxxxxxxxxxxxxxxxxxxxx:xxxxxxxxxxxxxxxxx:0:01" in your header)

Jaeger exporter directly is not available for the moment...

**Comment by josi02** [comment]
Hey @jufab ,

Thanks for the quick reply. :)

So does it mean that a separate running opentelemetry-collector component is required?
Do you have plan to implement a Jaeger exporter?

**Comment by jufab** [comment]
I use https://github.com/open-telemetry/opentelemetry-js for this library.
I wait for an implementation of Jaeger browser compatible to integrate it (like zipkin see #11)

Yes, you use opentelemetry-collector to receive all trace from Angular and export it to Jaeger.
Or you can imagine that use opentelemetry-collector to receive both otelcol "Angular" and Jaeger ".Net", and export it to Jaeger
