### ISSUE TITLE
Is there a way to add custom attributes for trace data using this library.

### ISSUE THREAD

**Issue by SunilManthenaG01** [jufab/opentelemetry-angular-interceptor#41]
I am using open telemetry collector and jaeger HTTP propagator to inject the trace id but for my span which is getting posted to the collector, I need to add some custom attributes with custom values. How can I add that attributes?

**Comment by jufab** [comment]
Hi @SunilManthenaG01 ,

You can add custom attributes in otelcolConfig like that (from example-app) : 

https://github.com/jufab/opentelemetry-angular-interceptor#opentelemetry-collector-configuration

```typescript
// Example to configure the angular-interceptor library
export const environment: IEnvironment = {
  production: false,
  urlTest: 'http://localhost:4200/api',
  openTelemetryConfig: {
    commonConfig: {
      console: true, // Display trace on console
      production: false, // Send Trace with BatchSpanProcessor (true) or SimpleSpanProcessor (false)
      serviceName: 'example-app', // Service name send in trace
      logBody: true, // true add body in a log, nothing otherwise
      probabilitySampler: '1', // 75% sampling
      logLevel:DiagLogLevel.ALL //ALL Log, DiagLogLevel is an Enum from @opentelemetry/api
    },
    otelcolConfig: {
      url: 'http://localhost:55681/v1/trace', // URL of opentelemetry collector
      attributes: {
        'my-custom': 'an-attribute',
        'my-other-custom': 'an-other-custom'
      }
    }
  },
  loggerConfig: {
    level: NgxLoggerLevel.DEBUG,
    disableConsoleLogging: false,
  }
};
```

So, in your collector you find this custom attributes : 

<img width="849" alt="jaeger" src="https://user-images.githubusercontent.com/25395032/116758174-d0d84d80-aa0f-11eb-8a27-aef479dc03c1.png">

or

<img width="1207" alt="zipkin" src="https://user-images.githubusercontent.com/25395032/116758197-d9c91f00-aa0f-11eb-9518-a6ce222ef9aa.png">

**Comment by SunilManthenaG01** [comment]
@jufab Thank you for your response. 
This way it's more static tags. If I need to send some dynamic values for a specific tag, that can not be possible with the above solution.

**Comment by jufab** [comment]
Yes, for the moment, there is no possibility to add dynamic values in current span.

Maybe I have an idea for that. I need times

Stay tuned

**Comment by SunilManthenaG01** [comment]
@jufab sounds good. Thank you

**Comment by jufab** [comment]
Ok, I think it's good. 
I release it soon!
