### ISSUE TITLE
Trying to hit Jaeger udp port  from otel collector config yaml file.

### ISSUE THREAD

**Issue by SunilManthenaG01** [jufab/opentelemetry-angular-interceptor#46]
Inside open telemetry config YAML, for the Jaeger exporters section currently, we are exporting to port 14250.
Is there a way we can hit any UDP port provided by jaeger.

Currently:
exporters:
  jaeger:
    endpoint: jaeger:14250
    insecure: true

Expected:
exporters:
  jaeger:
    endpoint: jaeger:6832
    insecure: true

All the below ports are supported by jaeger.
![image](https://user-images.githubusercontent.com/53482186/116899498-39d0e880-abfd-11eb-9528-b3c290e3ef93.png)

**Comment by jufab** [comment]
UDP and port 6832 are for Jaeger Agent not for collector.
But maybe for your this question around collector you should ask directly on OpenTelemetry collector.

I see you already do it => https://github.com/open-telemetry/opentelemetry-collector/discussions/3080 
so I close this issue
