### ISSUE TITLE
Incorrect Open Telemetry SpanKind value

### ISSUE THREAD

**Issue by Pete-PlaytimeSolutions** [jufab/opentelemetry-angular-interceptor#50]
Based on the recommendations mentioned here, https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-client.

The span.kind attribute should be set to "Client", not internal

also,

I think status.code should only use values  [Unset], Ok, Error. Currently being set to "1" for successful calls.
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#status

MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges, unless there was another error (e.g., network error receiving the response body; or 3xx codes with max redirects exceeded), in which case status MUST be set to Error.

For HTTP status codes in the 4xx and 5xx ranges, as well as any other code the client failed to interpret, status MUST be set to Error

**Comment by jufab** [comment]
Thx for this issue, fix is in progress.

For status.code at "1", it's for `Ok` as specified in proto for StatusCode https://github.com/open-telemetry/opentelemetry-proto/blob/8672494217bfc858e2a82a4e8c623d4a5530473a/opentelemetry/proto/trace/v1/trace.proto#L312

But you right, it must be `Unset` and not `Ok` for HTTP.
