### ISSUE TITLE
NG Serve Error

### ISSUE THREAD

**Issue by andreatosato** [jufab/opentelemetry-angular-interceptor#52]
Hi, 
I have this error when run **ng serve**:

```TS
Error: node_modules/@opentelemetry/tracing/build/src/export/ReadableSpan.d.ts:1:75 - error TS2614: Module '"@opentelemetry/api"' has no exported member 'TimedEvent'. Did you mean to use 'import TimedEvent from "@opentelemetry/api"' instead?

1 import { SpanKind, SpanStatus, SpanAttributes, HrTime, Link, SpanContext, TimedEvent } from '@opentelemetry/api';
                                                                            ~~~~~~~~~~
```

**Comment by julien-sugg** [comment]
Hi,

I just started playing with this module so it may not be 100% accurate. However, this appears to be related to your opentelemetry-js dependencies that may contain some version mismatch.

See [Compability Matrix](https://github.com/open-telemetry/opentelemetry-js#compatibility-matrix).

**Comment by andreatosato** [comment]
Thanks!
Now work fine

**Comment by jufab** [comment]
Version 0.20.0 is now released => You can now keep only this library and delete "@opentelemetry" in your dependencies from package.json (I try it on a new project angular 12)
