### ISSUE TITLE
Otel Collector exporter not working for Otel Collector v0.29.0

### ISSUE THREAD

**Issue by dgarciarubio** [jufab/opentelemetry-angular-interceptor#62]
The open telemetry collector has been updated in version 0.29.0 to require the `Content-Type: application/x-protobuf` request header as mentioned in open-telemetry/opentelemetry-collector#3540.

As of v0.22.0, this library is sending `Content-Type: application/json` in the request headers, thus making the collector return `404` and not processing the traces.

**Comment by dgarciarubio** [comment]
I think this is the same issue as open-telemetry/opentelemetry-js#2321

**Comment by jufab** [comment]
Yes!  😉

**Comment by dgarciarubio** [comment]
@jufab After reading your comment in the other issue, I realize the `application/json` header sent is correct, because `application/x-protobuf` is intended for binary-encoded Protobuf payloads.

I dont fully understand the problem right now, but I guess we can close this issue as soon as the other one is addressed and this repo is updated with the last version of opentelemetry-js.

**Comment by jufab** [comment]
Collector have a problem to in CORS with Allow-Control-Access-Credential.
Next collector release fix that.
So, we need : 
- New release collector
- bug fix open-telemetry/opentelemetry-js#2321

😊

**Comment by neminovno** [comment]
Is this issue the reason why example app fails with 404?
![chrome_Ve5c2UmNqv](https://user-images.githubusercontent.com/1468887/126539175-28871162-95d3-4ee3-8bca-e1fa4e9dfe22.png)

**Comment by jufab** [comment]
Yes, we need this fix from this issue open-telemetry/opentelemetry-js#2321

Use collector 0.28.0 for the moment...

**Comment by jufab** [comment]
Waiting for 0.25.0 contrib to release new version 0.25.0 and fix this issue.

**Comment by jufab** [comment]
All is OK now, I close this issue.
