### ISSUE TITLE
Question on ngx-logger alongside opentelemetry collector

### ISSUE THREAD

**Issue by Renaud009** [jufab/opentelemetry-angular-interceptor#64]
Hello,

In your interceptor-example (or logger documentation), how is your log debug event sent to the otel-collector? I don't see any ngx-logger event sent to the backend in the network? Is it correctly configured how am I wrong on what to expect?

Thanks in advance

**Comment by jufab** [comment]
Hi @Renaud009 

In my example, ngx-logger doesn't configure to send log (no `serverLoggingUrl` config) https://github.com/jufab/opentelemetry-angular-interceptor/blob/6586720cea856e4823a4efcbc5921d88ce6f4613/projects/interceptor-example/src/environments/environment.ts#L34-L37
only in navigator console.

**Comment by Renaud009** [comment]
Ok, I was thinking the lib supported sending **traces** as well as **logs** to an otel api.

Looks like configuration ngx-logger with serverLoggingUrl  and serverLogLevel work as logs a being sent remotely.

Wondering if such logs match otel collector api logs format since I struggle to find anything about that spec.

Thanks
