### ISSUE TITLE
Disable spans for HTTP requests, when using instrumentation component

### ISSUE THREAD

**Issue by DrNio13** [jufab/opentelemetry-angular-interceptor#72]
Hi,

In my `app.module.ts` I have added the following dependencies:

      // OtelCol Exporter Module
      OtelColExporterModule,
      // Composite Propagator Module
      CompositePropagatorModule,
      // OtelWebTracerModule to configure instrumentation component.
      OtelWebTracerModule.forRoot(environment.opentelemetryConfig),

`opentelemetryConfig` includes:

      ...
      instrumentationConfig: {
            xmlHttpRequest: false,
            fetch: false,
            documentLoad: false,
      }
      
I assumed all spans will be added "manually" by explicitly writing instrumentation code, since I am not using the interceptor module in my `app.module.ts`. Especially since the `xmlHttpRequest` flag is set to `false`.

However, HTTP POST and HTTP GET spans (only these type of requests are used in the project currently) are added automatically.  How can they be configured and/or how to disable them? Example:

![POST](https://user-images.githubusercontent.com/11769448/129530906-380bd007-3cd0-474f-9a8a-8f33bc7c1d26.PNG)

What is the usage of `xmlHttpRequest` flag if not disabling writing spans for each request?

**Comment by jufab** [comment]
I used instrumentation configuration `enabled` property but this configuration doesn't work.
The best way is to include or not the instrumentation plugin in register.

I'm going to fix that.

**Comment by jufab** [comment]
This fix is available on version 0.25.0 (I'm going to publish it 😊 )
