### ISSUE TITLE
 opentelemetry-angular-webpack-interceptor Error : http , https modules not found.

### ISSUE THREAD

**Issue by yunusemregl** [jufab/opentelemetry-angular-interceptor#76]
**Problem**
I implemented "opentelemetry-angular-webpack-interceptor" npm package from "https://www.npmjs.com/package/@jufab/opentelemetry-angular-webpack-interceptor". I just run npm install requirements and installed  custom webpack from here: "https://www.npmjs.com/package/@angular-builders/custom-webpack".
After this installments I also prepare environment.ts and app.module.ts files according to default configurations but after that when I tried to ng serve or build then following error messages appearing : 

**Error Message:**  
ERROR in ./node_modules/@opentelemetry/exporter-zipkin/build/src/zipkin.js
Module not found: Error: Can't resolve 'http' in 'D:\business\projects\myproject\node_modules\@opentelemetry\exporter-zipkin\build\src'
ERROR in ./node_modules/@opentelemetry/exporter-zipkin/build/src/zipkin.js
Module not found: Error: Can't resolve 'https' in 'D:\business\projects\myproject\node_modules\@opentelemetry\exporter-zipkin\build\src'

Do I need to do any other configuration ? could you help my about get it work  ? (By the way when I run the your example webpack project , its working properly but I can't implement it to my project due to errors like above.)

**Angular Version :** "~9.1.12"

**app.module.ts** 

import {OpenTelemetryInterceptorModule, CompositePropagatorModule} from '@jufab/opentelemetry-angular-interceptor';
import {ZipkinExporterModule, OpentelemetryInterceptorWebpackModule} from '@jufab/opentelemetry-angular-webpack-interceptor';

 imports: [
    BrowserModule,
    // Insert module OpenTelemetryInterceptorModule with configuration, HttpClientModule is used for interceptor
    OpenTelemetryInterceptorModule.forRoot(environment.openTelemetryConfig),
    // Extra configuration for OpentelemetryInterceptorWebpackModule
    OpentelemetryInterceptorWebpackModule.forRoot(environment.openTelemetryWebpackConfig),
    // Propagator (here, composite propagator)
    CompositePropagatorModule,
    // Zipkin exporter
    ZipkinExporterModule,
...]..

**environment.ts**

import * as packageInfo from '../../package.json';
import {OpenTelemetryConfig} from '@jufab/opentelemetry-angular-interceptor';
import {OpenTelemetryWebpackConfig} from '@jufab/opentelemetry-angular-webpack-interceptor';

interface IEnvironment {
  production: boolean;
  logLevel: string;
  version: string;
  openTelemetryConfig: OpenTelemetryConfig;
  openTelemetryWebpackConfig: OpenTelemetryWebpackConfig;
}

export const environment: IEnvironment = {
  production: false,
  version: '',
  logLevel: 'info', // loglevel options are ["info", "warn", "error"]
  openTelemetryConfig: {
    commonConfig: {
      console: true, // Display trace on console
      production: false, // Send Trace with BatchSpanProcessor (true) or SimpleSpanProcessor (false)
      serviceName: 'webclient-app', // Service name send in trace
      probabilitySampler: '1', // Samples a configurable percentage of traces, string value between '0' to '1'
    }
  },
  openTelemetryWebpackConfig: {
    zipkinConfig: {
      url: 'http://127.0.0.1:5000/client-trace'
      // url: 'http://localhost:9411/api/v2/spans'
    },
  }
};

**Comment by jufab** [comment]
I made this branch : https://github.com/jufab/opentelemetry-angular-interceptor/tree/ZipkinExporterExample
interceptor-example and instrumentation-example use ZipkinExporterModule and B3PropagatorModule (Zipkin Propagator)

About Propagator, all examples use CompositePropagator but you can use other one as described here (https://github.com/jufab/opentelemetry-angular-interceptor/tree/ZipkinExporterExample#propagator-module)

**Comment by yunusemregl** [comment]
**Thanks for your help.**
Hi @jufab , Thanks for your help. I implemented ZipkinExporterExample branch to my project. After I upgraded angular from 9.2 to 10.2 , now http interceptor module is working properly with 'HttpTraceContextPropagatorModule' propogator and 'ZipkinExporterModule' to export jaeger. 

**I have a bug when I use http requests with content-type:  x-protobuf**

When I am sending request which has header content-type="application/json" , then your interceptor adding 'traceparent' attribute (traceparent: 00-dfb5786cb0679db4c462daca30a88347-53a30d515bdbd700-01) to all reuqests header and sending jeager span requests. Now all is works like a charm and I can track all my traces, On the other hand,  when I am sending request which has header content-type="application/x-protobuf" then your interceptor does not include 'traceparent' attribute to request headers even if still sending span request to jaeger properly. But due to does not including traceparent attribute to requests headers I can't review my traces on jaeger ui.
Could you help me about this issue or x-protobuf request support?
