### ISSUE TITLE
Spans are not added to the correct context

### ISSUE THREAD

**Issue by DrNio13** [jufab/opentelemetry-angular-interceptor#77]
Hi,

While using the instrumentation module

```
    OtelColExporterModule,
    // Composite Propagator Module
    CompositePropagatorModule,
    // OtelWebTracerModule to configure instrumentation component.
    OtelWebTracerModule.forRoot(environment.opentelemetryConfig),
```

I have experienced that, sporadically, spans are not visible on Jaeger or they miss the context. 

For example: Starting a new trace and span on angular when clicking a button will trigger this code:

```
    this.contextManager.disable();
    this.contextManager.enable();
    const span = this.tracer
      .getTracer(`angular-interceptor`, '0.0.1')
      .startSpan(
        'some-post-request',
        {},
        this.contextManager.active()
      );
    this.contextManager._currentContext = api.setSpan(
      this.contextManager.active(),
      span
    );
    span.setStatus({
      code: SpanStatusCode.OK
    });
    span.end();
    this.apiService.sendPostRequest(`00-${span.context().traceId}-${span.context().spanId}-0${span.context().traceFlags}`);
```

which should create a span and trigger a POST request with the traceparent string, so that the api can read from the headers and add more spans to the trace.

On Jaeger the spans from the API are visible, and later on some spans might appear from the angular app due to Web Socket updates, but the "some-post-request" span from the angular app will not.

`OpenTelemetryConfig ` 

```
{
  production: false,
  opentelemetryConfig: {
    commonConfig: {
      console: false, 
      production: false,
      serviceName: 'test-service',
      probabilitySampler: '0.75', 
      logLevel: DiagLogLevel.ALL
    },
    otelcolConfig: {
      url: 'http://localhost:55681/v1/trace',
    },
    instrumentationConfig: {
      xmlHttpRequest: false,
      fetch: false,
      documentLoad: false,
    },
    jaegerPropagatorConfig: {
      customHeader: 'custom-header',
    }
  }
}
```

Code runs on Angular 11 and with these dependencies in package.json:

```
    "@opentelemetry/api": "^0.18.1",
    "@opentelemetry/context-zone-peer-dep": "^0.19.0",
    "@opentelemetry/exporter-collector": "^0.19.0",
    "@opentelemetry/exporter-zipkin": "^0.19.0",
    "@opentelemetry/instrumentation": "^0.19.0",
    "@opentelemetry/instrumentation-document-load": "^0.16.0",
    "@opentelemetry/instrumentation-fetch": "^0.19.0",
    "@opentelemetry/instrumentation-xml-http-request": "^0.19.0",
    "@opentelemetry/propagator-b3": "^0.19.0",
    "@opentelemetry/propagator-jaeger": "^0.19.0",
    "@opentelemetry/web": "^0.19.0",
```

Any ideas what can cause such a sporadic issue?

**Comment by jufab** [comment]
Version 0.25.0 is not released : I'm waiting for the release of opentelemetry-js-contrib.
So, this issue is not fixed for the moment : https://github.com/jufab/opentelemetry-angular-interceptor/issues/72#issuecomment-904077110
That's why you have some other span maybe with service name `test-service` in your Jaeger.

What the version of @jufab/opentelemetry-angular-interceptor? 0.24.0-1? and opentelemetry dependencies are in 0.24.0 too?

what is the version of your collector?
I see 
```
otelcolConfig: {
      url: 'http://localhost:55681/v1/trace',
    },
```

In newer version this is 
```
otelcolConfig: {
      url: 'http://localhost:55681/v1/traces',
},
```

**Comment by jufab** [comment]
I try this in instrumentation-example (with the same configuration as actually)
```
import { Component, OnInit } from '@angular/core';
import { trace, context, SpanStatusCode } from '@opentelemetry/api';
import * as api from '@opentelemetry/api';

@Component({
  selector: 'app-custo-send-span',
  templateUrl: './custo-send-span.component.html',
  styleUrls: ['./custo-send-span.component.css']
})
export class CustoSendSpanComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  sendSpan() {
    const tracer = trace.getTracerProvider().getTracer('test', '1.0.0');
    const span = tracer
      .startSpan(
        'some-post-request',
        {
          attributes: {
            test: 'test'
          },
          kind: api.SpanKind.INTERNAL,
        },
        context.active()
      );
    span.setStatus({
      code: SpanStatusCode.OK
    });
    span.end();
    console.log(`00-${span.spanContext().traceId}-${span.spanContext().spanId}-0${span.spanContext().traceFlags}`);
  }

}

```

This component send span :

<img width="1189" alt="span" src="https://user-images.githubusercontent.com/25395032/131401505-8451a032-97ce-4909-bc9c-5dabb0b7d489.png">

**Comment by DrNio13** [comment]
> Version 0.25.0 is not released : I'm waiting for the release of opentelemetry-js-contrib.
> So, this issue is not fixed for the moment : [#72 (comment)](https://github.com/jufab/opentelemetry-angular-interceptor/issues/72#issuecomment-904077110)
> That's why you have some other span maybe with service name `test-service` in your Jaeger.
> 
> What the version of @jufab/opentelemetry-angular-interceptor? 0.24.0-1? and opentelemetry dependencies are in 0.24.0 too?
> 
> what is the version of your collector?
> I see
> 
> ```
> otelcolConfig: {
>       url: 'http://localhost:55681/v1/trace',
>     },
> ```
> 
> In newer version this is
> 
> ```
> otelcolConfig: {
>       url: 'http://localhost:55681/v1/traces',
> },
> ```

```
    "@jufab/opentelemetry-angular-interceptor": "^0.19.0",

     "@opentelemetry/api": "^0.18.1",
    "@opentelemetry/context-zone-peer-dep": "^0.19.0",
    "@opentelemetry/exporter-collector": "^0.19.0",
    "@opentelemetry/exporter-zipkin": "^0.19.0",
    "@opentelemetry/instrumentation": "^0.19.0",
    "@opentelemetry/instrumentation-document-load": "^0.16.0",
    "@opentelemetry/instrumentation-fetch": "^0.19.0",
    "@opentelemetry/instrumentation-xml-http-request": "^0.19.0",
    "@opentelemetry/propagator-b3": "^0.19.0",
    "@opentelemetry/propagator-jaeger": "^0.19.0",
    "@opentelemetry/web": "^0.19.0",
```

So, I will try with new version of the dependencies and the new otelcolConfig url. 

The issue with the missing spans, is sporadic, meaning sometimes it works, sometimes not. I am not sure at the moment what is causing the spans to not appearing on some cases.

**Comment by DrNio13** [comment]
I updated to the current latest versions of openTelemetry and opentelemetry-angular-interceptor:

```
    "@jufab/opentelemetry-angular-interceptor": "^0.24.0-1",

     "@opentelemetry/api": "^1.0.1",
    "@opentelemetry/context-zone-peer-dep": "^0.24.0",
    "@opentelemetry/core": "^0.24.0",
    "@opentelemetry/exporter-collector": "^0.24.0",
    "@opentelemetry/exporter-zipkin": "^0.24.0",
    "@opentelemetry/instrumentation": "^0.24.0",
    "@opentelemetry/instrumentation-document-load": "^0.24.0",
    "@opentelemetry/instrumentation-fetch": "^0.24.0",
    "@opentelemetry/instrumentation-xml-http-request": "^0.24.0",
    "@opentelemetry/propagator-b3": "^0.24.0",
    "@opentelemetry/propagator-jaeger": "^0.24.0",
    "@opentelemetry/resources": "^0.24.0",
    "@opentelemetry/semantic-conventions": "^0.24.0",
    "@opentelemetry/tracing": "^0.24.0",
    "@opentelemetry/web": "^0.24.0",
```

Which caused a lot of errors. I fixed all of them except this: 

```
Error: src/app/shared/tracing/jaeger-propagator.service.ts:3:10 - error TS2305: Module '"../../../../node_modules/@opentelemetry/propagator-jaeger/build/src"' has no exported member 'JaegerHttpTracePropagator'.

3 import { JaegerHttpTracePropagator } from '@opentelemetry/propagator-jaeger'; 
```

My `open-telemetry-exporter.service.ts`

```

import {Injectable, Inject} from '@angular/core';
import {SpanExporter} from '@opentelemetry/tracing';
import {
  CollectorTraceExporter,
  collectorTypes,
} from '@opentelemetry/exporter-collector';
import {OpenTelemetryConfig, OpenTelemetryInjectConfig} from "@jufab/opentelemetry-angular-interceptor";

/**
 * OtelcolExporterService class
 */
@Injectable({
  providedIn: 'root',
})
export class OpenTelemetryExporterService {
  /**
   * CollectorExporterConfigBase
   */
  private otelcolConfig: collectorTypes.CollectorExporterConfigBase;

  /**
   * constructor
   * @param config OpenTelemetryConfig
   */
  constructor(
    @Inject(OpenTelemetryInjectConfig) config: OpenTelemetryConfig
  ) {
    this.otelcolConfig = {
      // serviceName: config.commonConfig.serviceName,
      url: config.otelcolConfig?.url,
      headers: config.otelcolConfig?.headers,
      attributes: config.otelcolConfig?.attributes
    };
  }

  /**
   * Return a CollectorExporter with the configuration
   * @return a CollectorExporter
   */
  getExporter(): SpanExporter {
    return new CollectorTraceExporter(this.otelcolConfig);
  }
}

```

Any ideas how to fix it?

**Comment by jufab** [comment]
I don't try this configuration but i think you must fix the version 0.24.0 (don't use ^ in version)
There is a  lot of breaking change in 0.25.0 => https://github.com/open-telemetry/opentelemetry-js/releases/tag/v0.25.0

**Comment by jufab** [comment]
> So, I will try with new version of the dependencies and the new otelcolConfig url.
> 
> The issue with the missing spans, is sporadic, meaning sometimes it works, sometimes not. I am not sure at the moment what is causing the spans to not appearing on some cases.

I reproduce it : I'm going to search a fix.

**Comment by jufab** [comment]
Ok, I found it.

Instrumentation example have a probabilitySampler configuration to 0.75 (75% sampling) so this is not sporadic but normal. 

Change value to 1 for sending all traces
