### ISSUE TITLE
how to provide opentelemetryConfig at outside instead of environment.ts

### ISSUE THREAD

**Issue by yunusemregl** [jufab/opentelemetry-angular-interceptor#78]
Hi  ,

I'am using http-interceptor module for jaeger tracing and its all working fine. Right now I need to take "probabilitySampler" value from env.js  or http call from my api. But its taking config from environment.ts file as following : 
OpenTelemetryInterceptorModule.forRoot(environment.openTelemetryConfig),

Is there a way to provide OpenTelemetryConfig inside of application with http api call or env.js ?

**Comment by jufab** [comment]
Hi @yunusemregl,

No solution for the moment.

See #61 , I think this is the same question but I try to find a solution (or if I need to modify code...) and I don't have one for the moment...
