### ISSUE TITLE
Dependencies out of date

### ISSUE THREAD

**Issue by icorne** [jufab/opentelemetry-angular-interceptor#80]
Hello,

After following the guide to install the dependencies, i got following errors:
                throw new Error("The target entry-point \"" + invalidTarget.entryPoint.name + "\" has missing dependencies:\n" +
                ^
Error: The target entry-point "@jufab/opentelemetry-angular-interceptor" has missing dependencies:
 - @opentelemetry/web
 - @opentelemetry/tracing

however, when I install these i get this warning: Which is what is installed in the guide

npm WARN deprecated @opentelemetry/tracing@0.24.0: Package renamed to @opentelemetry/sdk-trace-base
npm WARN deprecated @opentelemetry/web@0.24.0: Package renamed to @opentelemetry/sdk-trace-web

**Comment by jufab** [comment]
This "deprecated" dependencies come from `"@opentelemetry/instrumentation-document-load": "0.24.0"`

there is a 0.25.0 release now => I'm going to do a patch version (0.25.0-1)
