### ISSUE TITLE
Error: export 'HttpTraceContextPropagator'

### ISSUE THREAD

**Issue by andreatosato** [jufab/opentelemetry-angular-interceptor#86]
jufab-opentelemetry-angular-interceptor.js:572:19-45

Error: export 'HttpTraceContextPropagator' (imported as 'HttpTraceContextPropagator') was not found in '@opentelemetry/core' (possible exports: AlwaysOffSampler, AlwaysOnSampler, CompositePropagator, DEFAULT_ATTRIBUTE_COUNT_LIMIT, DEFAULT_ATTRIBUTE_VALUE_LENGTH_LIMIT, DEFAULT_ENVIRONMENT, ExportResultCode, ParentBasedSampler, RPCType, RandomIdGenerator, SDK_INFO, TRACE_PARENT_HEADER, TRACE_STATE_HEADER, TraceIdRatioBasedSampler, TraceState, TracesSamplerValues, VERSION, W3CBaggagePropagator, W3CTraceContextPropagator, baggageUtils, deleteRPCMetadata, getEnv, getRPCMetadata, globalErrorHandler, hexToBase64, hrTime, hrTimeDuration, hrTimeToMicroseconds, hrTimeToMilliseconds, hrTimeToNanoseconds, hrTimeToTimeStamp, isAttributeValue, isTimeInput, isTimeInputHrTime, isTracingSuppressed, isUrlIgnored, isWrapped, loggingErrorHandler, otperformance, parseEnvironment, parseTraceParent, sanitizeAttributes, setGlobalErrorHandler, setRPCMetadata, suppressTracing, timeInputToHrTime, unrefTimer, unsuppressTracing, urlMatches)

**Comment by andreatosato** [comment]
```
"dependencies": {
    "@angular/animations": "~12.2.0",
    "@angular/common": "~12.2.0",
    "@angular/compiler": "~12.2.0",
    "@angular/core": "~12.2.0",
    "@angular/forms": "~12.2.0",
    "@angular/platform-browser": "~12.2.0",
    "@angular/platform-browser-dynamic": "~12.2.0",
    "@angular/router": "~12.2.0",
    "@jufab/opentelemetry-angular-interceptor": "^0.25.0-2",
    "rxjs": "~6.6.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.8",
    "@angular/cli": "~12.2.8",
    "@angular/compiler-cli": "~12.2.0",
    "@opentelemetry/api": "^1.0.2",
    "@opentelemetry/context-zone-peer-dep": "^0.25.0",
    "@opentelemetry/core": "^1.0.0",
    "@opentelemetry/exporter-collector": "^0.25.0",
    "@opentelemetry/exporter-zipkin": "^0.25.0",
    "@opentelemetry/instrumentation": "^0.26.0",
    "@opentelemetry/instrumentation-document-load": "^0.24.0",
    "@opentelemetry/instrumentation-fetch": "^0.25.0",
    "@opentelemetry/instrumentation-xml-http-request": "^0.25.0",
    "@opentelemetry/propagator-aws-xray": "^0.25.0",
    "@opentelemetry/propagator-b3": "^0.25.0",
    "@opentelemetry/propagator-jaeger": "^0.25.0",
    "@opentelemetry/resources": "^1.0.0",
    "@opentelemetry/sdk-trace-base": "^1.0.0",
    "@opentelemetry/sdk-trace-web": "^0.25.0",
    "@opentelemetry/semantic-conventions": "^1.0.0",
    "@types/jasmine": "~3.8.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.8.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.3.5"
  }
```

**Comment by jufab** [comment]
Hi @andreatosato 

Change

> "@opentelemetry/core": "^1.0.0",

with 

> "@opentelemetry/core": "0.25.0",
