### ISSUE TITLE
How can I have interception without exporter?

### ISSUE THREAD

**Issue by dimio5** [jufab/opentelemetry-angular-interceptor#90]
First of all, thank you for this great package. You helped me grasp how a ton of manuals on open telemetry should work with angular. Much appreciated!

My use case is that we are interested in the traceparent header being sent to the server, but there is no requirement to collect traces into Jaeger or similar.

I use the OpenTelemetryInterceptorModule and the W3CTraceContextPropagatorModule, but they complain they want to resolve the IExporter interface.
But, I can't inject OtelColExporterModule or JaegerHttpTracePropagatorModule, because there is no requirement to collect traces from the client (actually this is considered a security issue .. I can't overcome that). If I inject them with empty urls, then the client just fails every so often with a call to a non existent url.

If I inject the ConsoleSpanExporterModule then I litter the console with unnecessary logging, making debugging the rest of the app very difficult. I would very much love to avoid that.

I tried to introduce my own NoopExporterModule which does nothing, just to make the compiler happy, but I can't declare the provider OTELCOL_EXPORTER because it is not part of the public api!!

So, I am wondering, am I missing something? 
If thats the way it should work, then can you expose the OTELCOL_EXPORTER or introduce a noop exporter in the package?

Thank you

**Comment by jufab** [comment]
Hi @dimio5,

Thank you for this clear explanation.

As you can see this issue is mentioned 2 times:
* One for the public export of tokens and interfaces
* Another for setting up the NoopSpanExporter

Your case seems legit, so i would like to share it with everyone with this feature.

**Comment by dimio5** [comment]
This is wonderful!
Thank you so much.

I will be waiting patiently for next release 🙏
